#src/controllers/authController.py
log_config.logger.error("User failed to login! Wrong credentials.", extra={'ip_address': request.remote_addr})